### PR TITLE
Revert "Updates to image pathing"

### PR DESCRIPTION
**Pull request by sinsukehlab**
Reverts #716

### Summary

PR #716 has broken the image paths. This PR will revert #716.

### Changes

- Revert #716(36751c8)
- Change simple HTML img tags into markdown

### Task list

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by adnangujjar98 — APPROVED** [review]

**Comment by ValkyrieSigrun** [comment]
i never sent this Account Owner J McNeil

**Comment by heiskr** [comment]
Hmm yeah it does look broken to me as well on main, I don't have context on https://github.com/skills/introduction-to-github/pull/716 either. Maybe we could use absolute URLs?

**Review by hectorsector — APPROVED** [review]

**Comment by hectorsector** [comment]
Thanks for the revert, @sinsukehlab. Merging this in - the relative references break the content for the majority of users. 

@WirelessLife since you merged in https://github.com/skills/introduction-to-github/pull/716, this change breaks the course so we're reverting it. We can chat about potential long term solutions for your use case if this way of referencing images isn't working.

**Comment by sinsukehlab** [comment]
In Markdown files in a repository, the root (`/`) indicates the root directory of the repository on the current branch. Relative references will indicate different paths between when written in `/.github/steps/*.md` and when written in `/README.md`. You might want to use the parent directory of the root (`/../`) to refer to things other than the files, such as Actions workflow runs, Projects, Wiki, Security alerts, Insights, Settings, and Tags, Releases, and Packages.
In comments on Issues, PRs, and Discussions, the root (`/`) indicates the [root](/) of https://github.com.

**Comment by sinsukehlab** [comment]
When written in `/.github/steps/*.md` (https://github.com/skills/introduction-to-github/tree/main/.github/steps/*.md):
`../`: `/.github` (https://github.com/skills/introduction-to-github/tree/main/.github/)
`../../`: `/` (https://github.com/skills/introduction-to-github/tree/main/)
`../../images/`: `/images/` (https://github.com/skills/introduction-to-github/tree/main/images/)

When written in `/README.md` (https://github.com/skills/introduction-to-github/blob/main/README.md or https://github.com/skills/introduction-to-github/tree/main/README.md):
`../`: https://github.com/skills/introduction-to-github.com/blob or https://github.com/skills/introduction-to-github/tree
`../../`: https://github.com/skills/introduction-to-github/
`../../images/`: https://github.com/skills/introduction-to-github/images/

**Comment by WirelessLife** [comment]
So there are plans to use this Codespace as part of a hand-on lab at Microsoft Build 2024. We are working with a company called Skillable who will be hosting the labs at the event. The issue with the broken image paths on Skillables platfform stemmed from how they were referenced in the project. Initially, Skillable had issues leveraging the absolute paths like /images/create-new-file.png, which worked fine when viewing the files directly on GitHub, but it caused issues when Skillable pulled the includes onto their platform.
 
When Skillable tried to include these images using relative paths like ../../images/create-new-file.png, they displayed properly on GitHub and within the Skillable client. I'm thinking this was because the relative path calculations were different depending on the location of the file including the image.
 
To fix this, the paths were updated to ../../images/create-new-file.png and submitted a pull request, which essentially navigated two directories up from the current location before locating the images directory. This ensured that regardless of where the file including the image was located within our project's directory structure, it would correctly resolve to the create-new-file.png image inside the images directory.

Seeing that this then broke another lab, I'm open to suggestions regarding next steps to ensure all labs are not affected.  Thank you all for your help on this.

**Comment by sinsukehlab** [comment]
:roll_eyes: 
@WirelessLife @SkillBL It's okay to use this course as a part of hands-on labs, but when you have trouble with implementation, you should first try to resolve it in your platform. When you definitely believe that the course itself should be changed, you should check if the course functions as expected before you submit (for contributors) or merge (for maintainers) PRs.
All GitHub Skills courses excluding [secure-code-game](/skills/secure-code-game) use the [action-update-step](/skills/action-update-step) action to update the step. When updating the step, README.md body is replaced with the corresponding Markdown file `/.github/steps/*.md`. Learners follow instructions from README.md. This is why relative references shouldn't be used in instructions.

> So there are plans to use this Codespace as part of future hand-on labs. We are working with a company called Skillable who will be hosting the labs at the event. The issue with the broken image paths on Skillables platfform stemmed from how they were referenced in the project. Initially, Skillable had issues leveraging the absolute paths like /images/create-new-file.png, which worked fine when viewing the files directly on GitHub, but it caused issues when Skillable pulled the includes onto their platform.
> 
> When Skillable tried to include these images using relative paths like ../../images/create-new-file.png, they displayed properly on GitHub and within the Skillable client. I'm thinking this was because the relative path calculations were different depending on the location of the file including the image.
> 
> To fix this, the paths were updated to ../../images/create-new-file.png and submitted a pull request, which essentially navigated two directories up from the current location before locating the images directory. This ensured that regardless of where the file including the image was located within our project's directory structure, it would correctly resolve to the create-new-file.png image inside the images directory.
> 
> Seeing that this then broke another lab, I'm open to suggestions regarding next steps to ensure all labs are not affected. Thank you all for your help on this.

**Review by preechapon-cmd — APPROVED** [review]

**Comment by duyphung123** [comment]
Dr

Vào 16:01 Th 2, 17 thg 2, 2025 seasand7 ***@***.***> đã viết:

**Pull request merged**
