### PR TITLE
Remove extra quotation marks in paths

### LINKED ISSUE #731: [Bug] Broken Images in Steps 2 and 3
### Summary

In the activity section for steps 2 and 3, some images are not displaying correctly due to an quotation mark at the end of the image URL. This issue affects the following images:

https://github.com/skills/introduction-to-github/blob/86a4beabd429a43f345e87c8116b6f30f0ad7af0/.github/steps/2-commit-a-file.md?plain=1#L36

https://github.com/skills/introduction-to-github/blob/86a4beabd429a43f345e87c8116b6f30f0ad7af0/.github/steps/2-commit-a-file.md?plain=1#L40

https://github.com/skills/introduction-to-github/blob/86a4beabd429a43f345e87c8116b6f30f0ad7af0/.github/steps/3-open-a-pull-request.md?plain=1#L30

### How to reproduce

1. Go to step 2 or 3
3. Scroll down to the activity section

image

image

### PR DESCRIPTION
**Pull request by sinsukehlab**
### Summary

In #719, I have left quotation marks (`"`) at the end of some image paths. This PR will remove them.

### Changes

Remove extra quotation marks

Closes: #731

### Task list

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by gracepark — APPROVED** [review]

**Review by Devante7 — APPROVED** [review]

**Comment by sinsukehlab** [comment]
@gracepark Please merge this PR as soon as possible.

**Review by 56494365 — APPROVED** [review]

**Comment by Tc69Cabusog** [comment]
I send 2000 my team send any data

**Review by krugre999 — APPROVED** [review]

**Comment by chientam01** [comment]
bukana91

**Comment by chientam01** [comment]
congtu89zx

**Review by BabydollSacca — COMMENTED** [review]
Hl y s

**Review by MaxMilionDataIQ — APPROVED** [review]

**Comment by BTCSERVICE1** [comment]
> @graceparkيرجى دمج هذه العلاقات العامة في أقرب وقت ممكن.

**Review by IreneSAvila — APPROVED** [review]

**Review by preechapon-cmd — APPROVED** [review]

**Review by a0983627353 — APPROVED** [review]

**Review by preechapon-cmd — APPROVED** [review]

**Review by Kkarwack7 — APPROVED** [review]

**Comment by hasnainhkhan** [comment]
merge

**Comment by urfaliesmer** [comment]
> ### Summary
> 
> In #719, I have left quotation marks (`"`) at the end of some image paths. This PR will remove them.
> 
> ### Changes
> 
> Remove extra quotation marks
> 
> 
> 
> Closes: #731
> 
> ### Task list
> 
> - [x] For workflow changes, I have verified the Actions workflows function as expected.
> - [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).
0xcf69d6830aaf8ab95c0cc7ca80c860a7e30234f2

**Comment by DawnawHsihsidawnawhsihsi** [comment]
### DawnawHsihsidawnawhsihsi

**Comment by DawnawHsihsidawnawhsihsi** [comment]
### **DawnawHsihsidawnawhsihsi**

Hello

**Comment by DawnawHsihsidawnawhsihsi** [comment]
DawnawHsihsidawnawhsihsi

Hello

**Comment by DawnawHsihsidawnawhsihsi** [comment]
> DawnawHsihsidawnawhsihsi

**Comment by DawnawHsihsidawnawhsihsi** [comment]
`DawnawHsihsidawnawhsihsi`

**Comment by DawnawHsihsidawnawhsihsi** [comment]
[DawnawHsihsidawnawhsihsi](url)

**Comment by badmonster068** [comment]
https://github.com/skills/introduction-to-github.git

**Comment by opof17pro** [comment]
Anamkashohrkontha

**Comment by opof17pro** [comment]
fardeen222345@gmail.com

**Review by preechapon-cmd — APPROVED** [review]

**Review by Kkarwack7 — APPROVED** [review]

**Comment by A-5058** [comment]
APPROVED

**Review by GODWthIN7 — APPROVED** [review]

**Review by Kkarwack7 — APPROVED** [review]

**Comment by Durronmilley** [comment]
Please approve

**Comment by GODWthIN7** [comment]
approved

**Review by Kkarwack7 — COMMENTED** [review]
Approve

**Pull request merged**
