### PR TITLE
Note

### PR DESCRIPTION
**Pull request by sinsukehlab**
### Summary
`**Note**` &rarr; `[!NOTE]`

### Changes

The GFM [highlighting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) has recently been updated. I have replaced the Note highlights.

#### Example use
```
> [!NOTE]
> This is a note.
```
How it is displayed:
> [!NOTE]
> This is a note.

### Discussed in https://github.com/orgs/skills/discussions/305

<div type='discussions-op-text'>

<sup>Originally posted by **sinsukehlab** July 21, 2023</sup>
An option to highlight a "Note" and "Warning" is updated.
I will open PRs to apply this change to the courses.

See: https://github.com/orgs/community/discussions/16925#discussioncomment-6506860
</div>

### Task list

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@sinsukehlab Thanks for submitting a PR! But let's hold off on incorporating this throughout Skills. Per that discussion, there are some changes still happening. We will keep an eye on it, though! 👀

**Comment by Aishwary-Gathe** [comment]
Good

**Comment by Cuengpribadi** [comment]
Pada tanggal Min, 20 Agt 2023 12.38, Aishwary-Gathe <
***@***.***> menulis:

**Review by TimmyTurner001 — APPROVED** [review]

**Comment by dhruvp66572** [comment]
Note

**Review by edwinbermudez — APPROVED** [review]
Approval

**Review by edwinbermudez — APPROVED** [review]

**Comment by sinsukehlab** [comment]
Recent update has just broken everything. :grimacing:
I will close this PR unless the feature is restored.

> ## Update - 14 November 2023
> * Add support for `[!TIP]` and `[!CAUTION]`.
> * Add support for alerts in Markdown files on [GitHub Mobile](https://github.com/mobile) apps. (pending a mobile app update)
> * Add support for various Markdown extensions such as Math rendering, relative links, task lists, animated image player and footnotes.
> * Prevent alerts from being nested within other elements.
> * The initial syntax using e.g. `**Note**` isn't supported any longer.

**Comment by Faphouse** [comment]
Automatically successful

**Comment by Faphouse** [comment]
OPPO F15

**Review by locadepatio — APPROVED** [review]

**Review by locadepatio — APPROVED** [review]

**Comment by RalphMaas** [comment]
Oke

**Review by RalphMaas — APPROVED** [review]

**Comment by Sw33tDisasteR** [comment]
Thanks a lot!

**Review by heiskr — APPROVED** [review]
Looks like it still doesn't show up in preview or in viewing the repo, yet when I play in this repo it renders correctly. Im going to go ahead and merge and hopefully it works.

**Review by preechapon-cmd — APPROVED** [review]

**Comment by Cheppard87** [comment]
> [!NOTE]
> This is a note.

**Review by Kkarwack7 — APPROVED** [review]

**Pull request merged**
