### PR TITLE
Open Source Course Knowlwdge Updated

### PR DESCRIPTION
**Pull request by AdityaSrivastava185**
Requesting to review changes .... 
### Summary
The intension to add changes in the project is , before actually contributing to the open source project and learning git and github for the open source , it is important to make learners understand about the fundamentals of open source and git and github , The Welcome page is now fully organised which clear concepts such as what is open source , why we should contribute to open source , basics terminologies of git and github and why do we use git and github and much more 

### Changes
1. Added next lesson file at the end of the each chapter for the better experience 
2. Added fundamentals and the concepts of open source contribution
3. Added fundamentals and concepts of git and github 
4. Types of softwares 
5. Course description and motivation

Closes: Enhance Course Content and Refactor Project Structure #832

### Task list

- [ ✅] For workflow changes, I have verified the Actions workflows function as expected.
- [ ✅] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by Johnson1s — CHANGES_REQUESTED** [review]
[heatlee1](https://github.com/Johnson1s/mempool)

**Comment by AdityaSrivastava185** [comment]
> [heatlee1](https://github.com/Johnson1s/mempool)

??

**Comment by heiskr** [comment]
👋🏼 Thank you for your pull request. This content would be out of scope for GitHub Skills. I'd recommend looking at our public docs at docs.github.com, the repository is https://github.com/github/docs.

**Review by Johnson1s — COMMENTED** [review]
🚀

**Pull request closed without merging**
