### PR TITLE
Fix grammar errors

### PR DESCRIPTION
**Pull request by abt8601**
### Why:

There are several grammatical errors in the article that may impact readability.

### What's being changed:

Grammatical errors listed below are fixed:

- edit to your project → edit your project
- what you changes you made → what changes you made
- in it's root → in its root

### Check off the following:

- [ ] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by Aa0541599451 — APPROVED** [review]
[](https://github.community/t/topic/229048?u=aa0541599451)

**Review by Ketherthe1st — APPROVED** [review]
Who who is thi

**Review by sinsukehlab — APPROVED** [review]
@dihydroJenoxide gentle reminder

**Review by AalOsman — APPROVED** [review]

**Review by dihydroJenoxide — APPROVED** [review]

**Comment by koukianis** [comment]
ok

Le sam. 24 sept. 2022 00:48, Jenni Christensen ***@***.***> a
écrit :

**Comment by koukianis** [comment]
ok

**Review by aliasimkazmi — COMMENTED** [review]
`For commits, you can enter a short commit message that describes what changes you made`

This can be an alternative

> For commits, you can enter a short commit message that describes the changes you have made.

**Review by Pagemarie2383 — COMMENTED** [review]
#154 

> ``

**Comment by Alfiekmote20** [comment]
Unsubscribe

Pada tanggal Sab, 12 Nov 2022 02.24, Pagemarie2383 ***@***.***>
menulis:

**Pull request merged**
